

[workspace]
members = [
    "crates/stryi_core",  # Contains core logic of the blockchain, also includes some important data structures
    "crates/stryi_node",  # Contains the Stryi blokchain node implementation 
    "crates/stryi_storage"# Contains the implementation of storages for UTXO's, blocks and mempool
]
resolver = "3"
