[workspace]
members = [
    "crates/stryi_core",
    "crates/stryi_node",
    "crates/stryi_storage",
    "crates/stryi_network",
    "crates/stryi_devkit",
    "crates/stryi_wallet"
]
resolver = "3"


[profile.dev]
incremental = true
codegen-units = 256
debug = 1


[profile.release]
lto = "fat"
codegen-units = 1 # for better LTO opts
