[workspace]
members = [
    "crates/stryi_core",
    "crates/stryi_node",
    "crates/stryi_storage",
    "crates/stryi_network",
    "crates/stryi_devkit",
    "crates/stryi_wallet"
]
resolver = "3"


[profile.dev]
incremental = true
codegen-units = 256
debug = 1


[profile.release]
lto = "fat"
codegen-units = 1 # for better LTO opts

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1" }
rand = "0.10.2"
tracing = "0.1.44"
postcard = { version = "1", features = ["use-std"] }
thiserror = "2.0.19"
blake3 = "1.8.5"
futures = "0.3.33"
rayon = "1.12.0"
k256 = { version = "0.14", features = ["serde", "ecdsa"] }
hex = "0.4.3"
serde_json = "1.0.151"
base64 = "0.23.0"
clap = { version = "4.6.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
comfy-table = "7.2.2"
indexmap = "2.14.0"
