network_rendezvous_mode  = "client"
network_rendezvous_address = "/ip4/127.0.0.1/tcp/4001"
network_listen_addr      = "/ip4/127.0.0.1/tcp/4003"
genesis_config_path     = "../demo_genesis.json"
start_mode = "join"

storage_path = "/tmp/stryi/client2"
grpc_sync_listen = "127.0.0.1:6003"
http_service_listen = "127.0.0.1:7003"
peer_key_path = "/tmp/stryi/client2/peer.stryi_keys"
