network_rendezvous_mode = "server"
network_listen_addr = "/ip4/127.0.0.1/tcp/4001"
grpc_sync_advertise = "/ip4/127.0.0.1/tcp/6001"
genesis_config_path = "../demo_genesis.json"
start_mode = "bootstrap"

miner_enabled = true
miner_reward_address = "@74e67a9ad28b9ac964b8a39779617271980b35bb"


storage_path = "/tmp/stryi/server"
grpc_sync_listen = "127.0.0.1:6001"
http_service_listen = "127.0.0.1:7001"
peer_key_path = "/tmp/stryi/server/peer.stryi_keys"
