[chain]
num_blocks = 275
seed = [{height = 1, value = 71441255032}, {height = 201, value = 99999999999}]
output_path = "/data/chain_reorg/"
genesis_path = "/config/e2e_genesis.json"
persistence_mode = "consensus_engine"

[blocks]
# This key is bound to address @69d168b888f9399791664057523a87621365b876 from demo_genesis.json
funding_key = "7c7e8339ddd63ff1f974534892b10d31b19812267a31a5d7f4fdb4efcbb40b99"
average_block_time_secs = 10
miner_address = "@2fdf51216b8d12feb0ecd4299446465cd8c013a5"
min_transactions_per_block = 10
max_transactions_per_block = 20
active_addresses_count = 25
need_undo = true
