network_rendezvous_mode = "client"


# This is the address defined in e2e_server_node.toml
network_rendezvous_address = "/dns4/server-node/tcp/2070"

network_listen_addr = "/ip4/0.0.0.0/tcp/3070"
start_mode = "join"

grpc_sync_listen = "0.0.0.0:3080"
grpc_sync_advertise = "/dns4/client-node-1/tcp/3080"
http_service_listen = "0.0.0.0:3090"
http_service_advertise = "/dns4/client-node-1/tcp/3090"
peer_key_path = "/data/keys/client1/peer.stryi_keys"
storage_path = "/tmp/stryi/client1"