[package]
name = "stryi_wallet"
edition = "2024"
version = "0.0.1"
authors = ["Rosenthall <rosenthall@riseup.net>"]
license = "BSD-3-Clause"


[[bin]]
name = "stryi-wallet"
path = "src/main.rs"


[dependencies]
stryi_core = { path = "../stryi_core" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
clap = { workspace = true }
reqwest = { version = "0.13", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
base64 = { workspace = true }
k256 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
dirs = "6"
anyhow = "1"
rustyline = "18"
colored = "3"
strsim = "0.11"

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
tempfile = "3"
