[package]
name = "stryi_wallet"
edition = "2024"
version = "0.0.1"
authors = ["Rosenthall <rosenthall@riseup.net>"]
license = "BSD-3-Clause"


[[bin]]
name = "stryi-wallet"
path = "src/main.rs"


[dependencies]
stryi_core = { path = "../stryi_core" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.6.4", features = ["derive"] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
postcard = { version = "1", features = ["use-std"] }
base64 = "0.23.0"
k256 = { version = "0.14", features = ["serde", "ecdsa"] }
hex = "0.4.3"
rand = "0.10.2"
dirs = "6"
anyhow = "1"
rustyline = "18"
colored = "3"
strsim = "0.11"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt", "macros"] }
tempfile = "3"
