services:
  chaingen:
    image: stryi-e2e-devkit:ci
    build:
      context: ../..
      dockerfile: e2e/docker/devkit.Dockerfile
    env_file: .env
    volumes:
      - stryi-e2e:/data
      - ../config:/config:ro
    environment:
      - RUST_LOG=${RUST_LOG}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  server-node:
    image: stryi-e2e-node:ci
    networks:
      - e2e
    build:
      context: ../..
      dockerfile: e2e/docker/node.Dockerfile
    env_file: .env
    volumes:
      - stryi-e2e:/data
      - ../config:/config:ro
    environment:
      - RUST_LOG=${RUST_LOG}
    restart: "no"
    stop_grace_period: 5s
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${SERVER_NODE_HTTP_API_PORT}/api/nodestate"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  client-node-1:
    image: stryi-e2e-node:ci
    networks:
      - e2e
    build:
      context: ../..
      dockerfile: e2e/docker/node.Dockerfile
    env_file: .env
    volumes:
      - stryi-e2e:/data
      - ../config:/config:ro
    environment:
      - RUST_LOG=${RUST_LOG}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${CLIENT1_NODE_HTTP_API_PORT}/api/nodestate"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: "no"
    stop_grace_period: 5s

  client-node-2:
    image: stryi-e2e-node:ci
    networks:
      - e2e
    build:
      context: ../..
      dockerfile: e2e/docker/node.Dockerfile
    env_file: .env
    volumes:
      - stryi-e2e:/data
      - ../config:/config:ro
    environment:
      - RUST_LOG=${RUST_LOG}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${CLIENT2_NODE_HTTP_API_PORT}/api/nodestate"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: "no"
    stop_grace_period: 5s

volumes:
  stryi-e2e:

networks:
  e2e:
