[package]
name = "stryi_storage"
version = "0.0.1"
edition = "2024"
authors = ["Rosenthall <rosenthall@riseup.net>"]
license = "BSD-3-Clause"

[dependencies]
fjall = "2.10.0"
stryi_core = { path = "../stryi_core" }
thiserror = "2"
tracing = "0.1.41"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.44.0", features = ["sync"] }
futures = "0.3.31"
blake3 = "1.8.2"

[dev-dependencies] # Need these to perform tests
tempfile = "3.1.16"
tokio = {version = "1.43.0", features = ["rt", "macros"]}
rand = "0.9.0"