[package]
name = "stryi_storage"
version = "0.0.1"
edition = "2024"
authors = ["Rosenthall <rosenthall@riseup.net>"]
license = "BSD-3-Clause"


[features]
chaingen = []

[dependencies]
fjall = "3.1.8"
stryi_core = { path = "../stryi_core" }
thiserror = { workspace = true }
tracing = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
futures = { workspace = true }
blake3 = { workspace = true }
futures-core = "0.3.33"
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies] # Need these to perform tests
tempfile = "3.27.0"
tokio = { workspace = true, features = ["rt", "macros"] }
rand = { workspace = true }
