[chain]
num_blocks = 300
seed = 42
output_path = "/tmp/testchain1"
genesis_path = "../demo_genesis.json"

[blocks]
average_block_time_secs = 10
miner_address = "@2fdf51216b8d12feb0ecd4299446465cd8c013a5"
min_transactions_per_block = 5
max_transactions_per_block = 25
active_addresses_count = 50
need_undo = false