[package]
name = "stryi_network"
version = "0.0.1"
edition = "2024"
description = "An implementation of the network protocol"
authors = ["Rosenthall <rosenthall@riseup.net>"]
license = "BSD-3-Clause"

[lib]
name = "stryi_network"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "sync", "time"] }
tokio-util = "0.7.19" # just for CancelationToken
tracing = { workspace = true }
libp2p = { version = "0.56.0", features = ["rendezvous", "ed25519", "ping", "serde", "gossipsub", "identify", "request-response", "cbor", "tcp", "noise", "yamux", "tokio", "macros", "dns"] }
futures = { workspace = true }
stryi_core = { path = "../stryi_core" }
postcard = { workspace = true }
rand = { workspace = true }
