[package]
name = "stryi_node"
version = "0.0.5"
edition = "2024"
description = "An implementation of the node for the Stryi Chain!"
authors = ["Rosenthall <rosenthall@riseup.net>"]
license = "BSD-3-Clause"
build = "build.rs"
default-run = "stryi-node"


[features]
telemetry = ["dep:console-subscriber"]
default = []

[[bin]]
name = "stryi-node"
path = "src/main.rs"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
console-subscriber = { version = "0.5.0", optional = true, default-features = false, features = ["parking_lot", "env-filter"] }
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread", "tracing", "signal"] }
tokio-stream = "0.1.19"
tokio-util = "0.7.19"
stryi_network = { path = "../stryi_network" }
stryi_core = { path = "../stryi_core" }
stryi_storage = { path = "../stryi_storage" }
futures-util = "0.3.33"
clap = { workspace = true }
tonic = { version = "0.14.6", features = ["tls-aws-lc"] }
tonic-prost = "0.14.6"
prost = "0.14.4"
serde_json = { workspace = true }
thiserror = { workspace = true }
colored = "3.1.1"
postcard = { workspace = true }
tower = "0.5.3"
zeroize = "1.9.0"
pem = "4.0.0"
rcgen = { version = "0.14.8", features = ["crypto", "x509-parser"] }
rustls-pki-types = "1.15.1"
pkcs8 = "0.11.0"
serde = { workspace = true }
figment = { version = "0.10.19", features = ["toml"] }
serde_with = "3.21.0"
http = "1.4.2"
http-body = "1.1.0"
axum = { version = "0.8.9", features = ["macros"] }
utoipa = "5.5.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
tower-http = { version = "0.7.0", features = ["compression-gzip", "trace", "set-header", "validate-request"] }
base64 = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
indicatif = "0.18.6"
comfy-table = { workspace = true }
multiaddr = "0.18.2"

[dev-dependencies]
x509-parser = "0.18.1"

[build-dependencies]
prost = "0.14.4"
tonic-prost-build = "0.14.6"
