[package]
name = "stryi_devkit"
version = "0.0.1"
edition = "2024"
authors = ["Rosenthall <rosenthall@riseup.net>"]

[[bin]]
name = "stryi-devkit"
path = "src/main.rs"


[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stryi_core = { path = "../stryi_core" }
stryi_storage = { path = "../stryi_storage", features = ["chaingen"] }
toml = "1.1.3"
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
rand_chacha = "0.10.0"
rayon = { workspace = true }
postcard = { workspace = true }
k256 = { workspace = true }
tracing = { workspace = true }
indexmap = { workspace = true }
